# Data Manipulation with Pandas and NumPy
Data manipulation is the process of changing, organizing, or transforming data to make it more useful, readable, or suitable for analysis. It involves tasks like cleaning, filtering, sorting, grouping, or calculating new values from existing data.

Tools like Pandas and NumPy, popular Python libraries, are often used to streamline these tasks. Pandas excels at handling structured data, like tables of crypto trades, for filtering or grouping, while NumPy supports fast numerical computations, such as calculating average prices or returns.

For instance, a crypto investor might manipulate data by filtering trades to show only Bitcoin transactions over $5,000, sorting them by timestamp to track price movements, and aggregating daily totals to assess trading volume. This helps uncover trends, optimize strategies, and ensure data accuracy, ultimately supporting better decisions in the fast-paced crypto market.

## Pandas
Pandas is a popular Python library used for working with data. It helps you load, clean, analyze, and manipulate data easily. Think of it like an Excel spreadsheet in Python! It’s great for handling tables of data.

### _Key Concepts_
Series: A single column of data (like a list with labels).

Index: Labels for rows, helping you identify and access data.

You can load data from files (CSV, Excel, etc.), manipulate it, and save it back.

### Installing / Importing Pandas

In [276]:
# ! pip install -r requirements.txt       # installs all the dependencies in the requirements.txt file

! pip freeze > requirements.txt         # used to add the new dependencies to the requirements.txt file 

In [277]:
import pandas as pd

### Series

In [278]:
vol = [15000, 57643, 200000, 50000]

data = pd.Series(vol)

print(data)

0     15000
1     57643
2    200000
3     50000
dtype: int64


##### useful series methods

data.head()

data.describe()

data.mean()

data.prod()

data.sum()

data.tail()

In [279]:
data.describe()

count         4.000000
mean      80660.750000
std       81696.774899
min       15000.000000
25%       41250.000000
50%       53821.500000
75%       93232.250000
max      200000.000000
dtype: float64

In [280]:
data.sum()

np.int64(322643)

In [281]:
print(data.prod())

8646450000000000000


In [282]:
values = [15000, '57643', 200000, False]

data2 = pd.Series(values)

print(data2)

0     15000
1     57643
2    200000
3     False
dtype: object


In [283]:
data.loc[3]

np.int64(50000)

### Create a DataFrame
A DataFrame is like a table with rows and columns. Let’s create one with sample cryptocurrency data (e.g., coin names, prices, and trade volumes).

In [284]:
# Create a dictionary with crypto data

data = {
    'Coin': ['Bitcoin', 'Ethereum', 'Ripple', 'Litecoin'],
    'Price': [45000,3000, 0.85, 120],
    'Volume': [15000, " ", 200000, 50000]
}

df = pd.DataFrame(data)   # pd is a module, DataFrame is a class/function in pandas

print(df)

       Coin     Price  Volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00        
2    Ripple      0.85  200000
3  Litecoin    120.00   50000


### Explore Data

In [285]:
df

Coin     Price  Volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00        
2    Ripple      0.85  200000
3  Litecoin    120.00   50000

In [286]:
print(df.head())

       Coin     Price  Volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00        
2    Ripple      0.85  200000
3  Litecoin    120.00   50000


In [287]:
print(df.tail())

       Coin     Price  Volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00        
2    Ripple      0.85  200000
3  Litecoin    120.00   50000


In [288]:
# df.head(2)

# or 

df.head(n=2)

Coin    Price Volume
0   Bitcoin  45000.0  15000
1  Ethereum   3000.0

In [289]:
df.loc[0]

Coin      Bitcoin
Price     45000.0
Volume      15000
Name: 0, dtype: object

In [290]:
df.loc[2]

Coin      Ripple
Price       0.85
Volume    200000
Name: 2, dtype: object

In [291]:
df.loc[[0,2,3]]

Coin     Price  Volume
0   Bitcoin  45000.00   15000
2    Ripple      0.85  200000
3  Litecoin    120.00   50000

In [292]:
df.loc[1, 'Volume']

' '

In [293]:
df.loc[1, 'Volume'] = 60000

print(df.loc[1, 'Volume'])

60000


In [294]:
df.loc[3, ['Coin', 'Price']]

Coin     Litecoin
Price       120.0
Name: 3, dtype: object

### Get info

In [295]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Coin    4 non-null      object 
 1   Price   4 non-null      float64
 2   Volume  4 non-null      object 
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes


### Basic Data Manipulation

In [296]:
# select a specific column

print(df[['Coin', 'Price']])

       Coin     Price
0   Bitcoin  45000.00
1  Ethereum   3000.00
2    Ripple      0.85
3  Litecoin    120.00


In [297]:
print(df['Coin'])

0     Bitcoin
1    Ethereum
2      Ripple
3    Litecoin
Name: Coin, dtype: object


### Filtering through the rows

In [298]:
df['Price'] > 100

0     True
1     True
2    False
3     True
Name: Price, dtype: bool

In [299]:
print(df[df['Price'] > 100])

       Coin    Price Volume
0   Bitcoin  45000.0  15000
1  Ethereum   3000.0  60000
3  Litecoin    120.0  50000


In [300]:
df

Coin     Price  Volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00   60000
2    Ripple      0.85  200000
3  Litecoin    120.00   50000

In [301]:
df[df['Price'] >= 300]

Coin    Price Volume
0   Bitcoin  45000.0  15000
1  Ethereum   3000.0  60000

or

In [302]:
df.query('Price >= 3000')

Coin    Price Volume
0   Bitcoin  45000.0  15000
1  Ethereum   3000.0  60000

using logical operators and(&) and or(|)

In [303]:
df[(df['Price'] == 67600) | (df['Volume'] >= 200000) | (df['Coin'] == 'Litecoin')]

Coin   Price  Volume
2    Ripple    0.85  200000
3  Litecoin  120.00   50000

In [304]:
# Ensure 'Volume' is numeric for comparison
df['Volume'] = pd.to_numeric(df['Volume'], errors='coerce')

# Filter rows where Price < 1 and Volume >= 1
df[(df['Price'] < 1) & (df['Volume'] >= 1)]

Coin  Price  Volume
2  Ripple   0.85  200000

In [305]:
df.query('  Price < 1 & Volume >= 1  ')

Coin  Price  Volume
2  Ripple   0.85  200000

In [306]:
df.query('  (Price < 1) & (Volume >= 1)  ')

Coin  Price  Volume
2  Ripple   0.85  200000

### Sort Data

Sort by a column like Price in asc or desc order

In [307]:
print(df.sort_values('Price'))  # sorts in asc order by default

       Coin     Price  Volume
2    Ripple      0.85  200000
3  Litecoin    120.00   50000
1  Ethereum   3000.00   60000
0   Bitcoin  45000.00   15000


In [308]:
print(df.sort_values(by ='Price')) 

       Coin     Price  Volume
2    Ripple      0.85  200000
3  Litecoin    120.00   50000
1  Ethereum   3000.00   60000
0   Bitcoin  45000.00   15000


In [309]:
print(df.sort_values('Price', ascending = False))  # sorts in desc order 

       Coin     Price  Volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00   60000
3  Litecoin    120.00   50000
2    Ripple      0.85  200000


### Add a new column

In [310]:
df['Price_after_2pct'] = df['Price'] * 1.02

print(df)

       Coin     Price  Volume  Price_after_2pct
0   Bitcoin  45000.00   15000         45900.000
1  Ethereum   3000.00   60000          3060.000
2    Ripple      0.85  200000             0.867
3  Litecoin    120.00   50000           122.400


### Statistical analysis/description/metrics of the dataframe

In [311]:
df.describe()           # used to investigate data

Price         Volume  Price_after_2pct
count      4.000000       4.000000          4.000000
mean   12030.212500   81250.000000      12270.816750
std    22023.550649   81483.638439      22464.021662
min        0.850000   15000.000000          0.867000
25%       90.212500   41250.000000         92.016750
50%     1560.000000   55000.000000       1591.200000
75%    13500.000000   95000.000000      13770.000000
max    45000.000000  200000.000000      45900.000000

You can use the count to tell if there is missing row or not....count gives the number of rows

if the max, 25,50,75 percentiles are giving an outrageous amount compared to the mean, that's a good indicator of an outlier or the data is not correct.

In [312]:
df.to_csv('crypto_data.csv', index = False)

In [315]:
df = pd.read_csv('crypto_data.csv')

data = pd.DataFrame(df)

data

Coin     Price  Volume  Price_after_2pct
0   Bitcoin  45000.00   15000         45900.000
1  Ethereum   3000.00   60000          3060.000
2    Ripple      0.85  200000             0.867
3  Litecoin    120.00   50000           122.400

In [316]:
data.loc[1,'Volume']= 65484

data

Coin     Price  Volume  Price_after_2pct
0   Bitcoin  45000.00   15000         45900.000
1  Ethereum   3000.00   65484          3060.000
2    Ripple      0.85  200000             0.867
3  Litecoin    120.00   50000           122.400

### Styling DataFrames

##### example 1

In [241]:
import pandas as pd

# Sample DataFrame
data = pd.DataFrame({
    'A': [1, 5, 3],
    'B': [4, 2, 6]
})

# Apply styling
styled_data = data.style \
    .highlight_max(color='lightgreen') \
    .highlight_min(color='pink')

# Save to HTML
output_file = "styled_table.html"
styled_data.to_html(output_file)

print(f"Styled table saved to: {output_file}")

Styled table saved to: styled_table.html


In [242]:
# open the HTML file in your browser
import webbrowser
webbrowser.open(output_file)

True

##### other examples

In [243]:
data = pd.DataFrame(pd.read_csv('crypto_data.csv'))

data

Coin     Price  Volume  Price_after_2pct
0   Bitcoin  45000.00   15000         45900.000
1  Ethereum   3000.00   60000          3060.000
2    Ripple      0.85  200000             0.867
3  Litecoin    120.00   50000           122.400

In [244]:
data['Volume'] = data['Volume'].replace(" ", np.nan)  # Replace blank with NaN
data['Volume'] = data['Volume'].astype(float)         # Convert to float (if needed)
data['Volume'] = data['Volume'].fillna(0).astype(int) # Fill NaN with 0 and convert to int
data

Coin     Price  Volume  Price_after_2pct
0   Bitcoin  45000.00   15000         45900.000
1  Ethereum   3000.00   60000          3060.000
2    Ripple      0.85  200000             0.867
3  Litecoin    120.00   50000           122.400

In [245]:
# Calculate the mean of non-zero volumes
mean_volume = data.loc[data['Volume'] != 0, 'Volume'].mean()

# Replace all 0 values in 'Volume' with the mean value (converted to int)
data['Volume'] = data['Volume'].replace(0, int(mean_volume))

# Display the updated DataFrame
data

Coin     Price  Volume  Price_after_2pct
0   Bitcoin  45000.00   15000         45900.000
1  Ethereum   3000.00   60000          3060.000
2    Ripple      0.85  200000             0.867
3  Litecoin    120.00   50000           122.400

In [246]:
# Apply styling
styled_data = data.style \
    .highlight_max(color='lightgreen') \
    .highlight_min(color='pink')

# Save to HTML
output_file = "styled_table1.html"
styled_data.to_html(output_file)

print(f"Styled table saved to: {output_file}")

# open the HTML file in your browser
webbrowser.open(output_file)

Styled table saved to: styled_table1.html


True

In [247]:
# Apply styling
styled_data = data.style \
    .highlight_between(subset=['Volume'], left=15000, right=90000)

# Save to HTML
output_file = "styled_table2.html"
styled_data.to_html(output_file)

print(f"Styled table saved to: {output_file}")

# open the HTML file in your browser
webbrowser.open(output_file)

Styled table saved to: styled_table2.html


True

```
The backslash \ is used in Python to indicate that a statement continues on the next line. In your code, it allows you to split a long method chain across multiple lines for better readability.
Without the backslash, Python would treat each line as a separate statement and cause a syntax error. So yes, it's important when you want to break up a long line of code.
```

In [248]:
# Apply styling
styled_data = data[['Price', 'Volume']].style.bar(color='blue')

# Save to HTML
output_file = "styled_table3.html"
styled_data.to_html(output_file)

print(f"Styled table saved to: {output_file}")

# open the HTML file in your browser
webbrowser.open(output_file)

Styled table saved to: styled_table3.html


True

### Creating a pivot table to summarize Volume by Coin

In [249]:
pivot_table = data.pivot_table(values='Volume', index='Coin', aggfunc='sum')
print(pivot_table)

          Volume
Coin            
Bitcoin    15000
Ethereum   60000
Litecoin   50000
Ripple    200000


### Data cleaning with Pandas

In [321]:
import openpyxl

dataa = pd.read_excel(r'C:\Users\Jo$h\Desktop\HiiT Python Course\Python of DA\Dirtydata.xlsx')

dataa

CustomerID First_name    Last_Name  Phone_Number  \
0         1001      Frodo      Baggins  123-545-5421   
1         1002       Abed        Nadir  123/643/9775   
2         1003     Walter       /White   709/909/901   
3         1004     Dwayne      Shurlle  123-543-2345   
4         1005       John         Snow  876|678|3469   
5         1006        Ron      Swanson  304-762-2467   
6         1007       Jeff       Winger           NaN   
7         1008   Sherlock       Holmes  876|678|3469   
8         1009    Gandalf          NaN           N/a   
9         1010      Peter    ...Parker  123-545-5421   
10        1011      Sammy       George           NaN   
11        1012      Harry       Potter   706#695#039   
12        1013        Don       Draper  123-543-2345   
13        1014     Leslie      Houston  876|678|3469   
14        1015       Toby  Richardson_  304-762-2467   
15        1016        Ron      Weasley  123-545-5421   
16        1017    Michael        Scott  123/643/9775   
17        1018      Clark         Kent   709/909/901   
18        1019      Creed       Braton           N/a   
19        1020     Anakin    Skywalker  876|678|3469   
20        1020     Anakin    Skywalker  876|678|3469   

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes             No   
1                     93 West Main Street              No            Yes   
2                      298 Drugs Driveway               N            NaN   
3   980 Paper Avenue, Pennsylvania, 18503             Yes            Yes   
4                        123 Dragons Road               Y             No   
5                        768 City Parkway             Yes            Yes   
6                       1209 South Street              No             No   
7                           98 Clue Drive               N             No   
8                        123 Middle Earth             Yes            NaN   
9              25th Main Street, New York             Yes             No   
10                  612 Shire Lane, Shire             Yes             No   
11                   2394 Hogwarts Avenue               Y            NaN   
12                       2039 Main Street             Yes              N   
13                       343 City Parkway             Yes             No   
14                          214 HR Avenue               Y             No   
15                   2395 Hogwarts Avenue              No              N   
16         121 Paper Avenue, Pennsylvania             Yes             No   
17                        3496 Super Lane               Y            NaN   
18                                    N/a             N/a            Yes   
19            910 Tatooine Road, Tatooine             Yes              N   
20            910 Tatooine Road, Tatooine             Yes              N   

    Not_Useful_Column        DOB  
0                True 2004-02-14  
1               False 2015-08-19  
2                True 2022-04-10  
3                True 2023-12-03  
4                True 2017-09-26  
5                True 1992-03-24  
6               False 2012-04-19  
7               False 2010-04-04  
8               False 2019-08-22  
9                True 1991-02-19  
10               True 2010-12-21  
11               True 1998-05-03  
12              False 2020-04-01  
13              False 2002-05-28  
14              False 1994-06-01  
15              False 2009-06-25  
16              False 2024-02-26  
17               True 2025-01-19  
18               True 1993-05-22  
19               True 1998-12-21  
20               True 1993-03-22

#### Checking Null Values

In [331]:
# dataa.isnull()
# dataa.isna()

dataa.isnull().sum()
# dataa.isna().sum()

## both are the same

CustomerID           0
First_name           0
Last_Name            1
Phone_Number         2
Address              0
Paying Customer      0
Do_Not_Contact       4
Not_Useful_Column    0
DOB                  0
dtype: int64

#### Checking Non-null values

In [333]:
# dataa.notnull().sum()
dataa.notna().sum()

CustomerID           21
First_name           21
Last_Name            20
Phone_Number         19
Address              21
Paying Customer      21
Do_Not_Contact       17
Not_Useful_Column    21
DOB                  21
dtype: int64

### checking for duplicates

In [337]:
print(dataa.duplicated().sum())

# every row is unique...no duplicates
# however index 19 and 20 are almost duplicates but differ because of the DOB field

0


In [340]:
print(dataa['CustomerID'].duplicated().sum())

1


_check more in the `python pandas dataframe pdf`_

### Common Pandas DataFrame Methods

#### **1. Data Inspection & Summary**
- `df.head(n=5)` → Returns the first `n` rows (default: 5).
- `df.tail(n=5)` → Returns the last `n` rows (default: 5).
- `df.info()` → Displays column data types, non-null counts, and memory usage.
- `df.describe()` → Provides summary statistics (count, mean, std, min, max, etc.).
- `df.shape` → Returns a tuple `(rows, columns)`.
- `df.columns` → Returns column names as an Index object.
- `df.index` → Returns the index (row labels).
- `df.dtypes` → Returns data types of all columns.
- `df.memory_usage()` → Shows memory consumption of columns.

---

#### **2. Data Selection & Filtering**
- `df['col']` or `df.col` → Selects a single column (returns Series).
- `df[['col1', 'col2']]` → Selects multiple columns (returns DataFrame).
- `df.loc[row_label, col_label]` → Label-based selection.
- `df.iloc[row_idx, col_idx]` → Position-based (integer index) selection.
- `df.query("condition")` → Filters rows using a query string (e.g., `"age > 30"`).
- `df.filter(items=['col1', 'col2'])` → Selects columns by name.
- `df.sample(n=3)` → Randomly samples `n` rows.
- `df.isin(values)` → Filters rows containing specified values.
- `df.where(cond)` → Keeps values where condition is True, else NaN.
- `df.mask(cond)` → Opposite of where (replaces where condition is True).

---

#### **3. Data Cleaning & Manipulation**
- `df.drop(labels, axis=0/1)` → Drops rows (`axis=0`) or columns (`axis=1`).
  - Examples: 
    - `df.drop(['row1', 'row2'], axis=0)`
    - `df.drop(['col1', 'col2'], axis=1)`
    - `df.drop(index = 3)` → droping the 4th row
- `df.dropna()` → Removes rows/columns with missing values.
- `df.drop_duplicates()` → Removes duplicate rows.
- `df.drop(columns=['col'])` → Drops specified columns (alternative syntax).
- `df.fillna(value)` → Fills missing values with `value` or method (e.g., `ffill`).
- `df.rename(columns={'old':'new'})` → Renames columns.
- `df.sort_values(by='col')` → Sorts by column values (ascending/descending).
- `df.reset_index(drop=True)` → Resets index (optional: `drop=True` removes old index).
- `df.insert(loc, column, value)` → Inserts column at specified position.
- `df.pop('col')` → Removes and returns a column (as Series).
- `df.replace(old_val, new_val)` → Replaces values in DataFrame.
- `df.clip(lower, upper)` → Trims values outside a threshold.
- `df.explode('col')` → Transforms each element in a list-like column to a row.

---

#### **4. Aggregation & Grouping**
- `df.groupby('col').agg(['mean', 'sum'])` → Groups and aggregates data.
- `df.pivot_table(values='val', index='row', columns='col')` → Creates a pivot table.
- `df.mean()`, `df.sum()`, `df.min()`, `df.max()` → Column-wise aggregations.
- `df.value_counts()` → Counts unique values in a column.
- `df.nunique()` → Counts unique values per column.
- `df.corr()` → Computes pairwise correlation of columns.
- `df.cov()` → Computes covariance matrix.

---

#### **5. Combining DataFrames**
- `pd.concat([df1, df2])` → Concatenates vertically (`axis=0`) or horizontally (`axis=1`).
- `df1.merge(df2, on='key')` → SQL-style joins (`inner`, `left`, `right`, `outer`).
- `df1.join(df2)` → Joins on index.
- `df.update(other_df)` → Modifies in-place with non-NA values from another DataFrame.
- `pd.merge_asof()` → Asof merge (for time series data).

---

#### **6. File I/O**
- `df.to_csv('file.csv')` → Saves DataFrame to CSV.
- `pd.read_csv('file.csv')` → Reads CSV into DataFrame.
- `df.to_excel('file.xlsx')` → Saves to Excel.
- `pd.read_excel('file.xlsx')` → Reads Excel file.
- `df.to_json('file.json')` → Saves to JSON format.
- `df.to_pickle('file.pkl')` → Saves as pickle file (preserves dtypes).
- `pd.read_pickle('file.pkl')` → Reads pickle file.

---

#### **7. Other Useful Methods**
- `df.isna()` → Checks for missing values (returns boolean DataFrame).
- `df.duplicated()` → Finds duplicate rows.
- `df.apply(func)` → Applies a function to each column/row.
- `df.applymap(func)` → Applies function element-wise.
- `df.assign(new_col=df['col'] * 2)` → Adds a new column.
- `df.copy()` → Creates a deep copy of the DataFrame.
- `df.pipe(func)` → Chains operations (functional programming style).
- `df.eval('expression')` → Evaluates string expression.
- `df.compare(other_df)` → Shows differences between DataFrames.
- `pivot_table = data.pivot_table(values='Volume', index='Coin', aggfunc='sum')` → Create a pivot table to summarize Volume by Coin

## Numpy

NumPy is a powerful Python library for numerical computations, especially useful for working with arrays (lists of numbers) and performing fast mathematical operations. It’s a foundation for data manipulation, often used alongside Pandas, and is great for tasks like calculations, statistics, and handling crypto-related data. Below, I’ll walk you through the basics step by step—installing NumPy, creating arrays, and performing common operations with simple code. This is beginner-friendly and straightforward.

### Installing and Importing Numpy

In [19]:
# already in requirements.txt file and installed from the beginning

import numpy as np

### Creating a Numpy array

A NumPy array is like a list but optimized for math and faster operations. Let’s create arrays with sample cryptocurrency data (e.g., coin prices and trade volumes).

In [20]:
prices = np.array([45000, 50000, 40000, 20000])         # np is a module....array() is a function/class in np
print(prices)       

[45000 50000 40000 20000]


In [21]:
prices.shape

(4,)

### Data type check

In [22]:
print(prices.dtype)

int64


### Basic data manipulation

In [23]:
prices = np.array([45000, 50000, 40000, 20000])

# adding 1000 to all prices

prices_plus_1000 = prices + 1000

print(prices_plus_1000)

[46000 51000 41000 21000]


In [24]:
# compute for 2% increase in price

prices_s = np.array([46000, 51000, 41000, 21000])

price_increase = prices + 1.02

print(price_increase)

[45001.02 50001.02 40001.02 20001.02]


In [25]:
# filter data

higher_price = prices_s[prices_s > 20000]

print(higher_price)

[46000 51000 41000 21000]


### Basic Statistical Functions using Numpy

In [ ]:
volume = np.array([500000, 300000, 200000, 100000])

print("\nStatistics for Volume: ")      # the \n means go to the next line

print("Mean (Average): ", np.mean(volume)) # Average Volume
print("Minimum: ", np.min(volume)) # Minimum volume
print("Maximum: ", np.max(volume)) # Maximum Volume
print("Sum: ", np.sum(volume)) # Total sum of volumes
print("Standard Dev (Volatility): ", np.std(volume))


Statistics for Volume: 
Mean (Average):  275000.0
Minimum:  100000
Maximum:  500000
Sum:  1100000
Standard Dev (Volatility):  147901.9945774904


### Work with 2D Arrays

NumPy can handle multi-dimensional arrays. Let’s combine our data into a 2D array (like a table).

In [50]:
# Create 2D array

crypto_data = np.array([
    [45000, 5000],
    [30000, 28000],
    [11998, 8943]
])


print(crypto_data)

[[45000  5000]
 [30000 28000]
 [11998  8943]]


In [53]:
# Accessing Row

crypto_data[2]

array([11998,  8943])

In [61]:
# Accessing column

crypto_data[:,1]

array([ 5000, 28000,  8943])